"""Contains variables with error codes to exit interpret with."""
ERR_MISSING_ARG = 10
ERR_READ_INPUT = 11
ERR_XML_FORMAT = 31
ERR_XML_STRUC = 32
ERR_SEMANTICS = 52
ERR_OPERAND = 53
ERR_VARIABLE = 54
ERR_FRAME = 55
ERR_MISSING_VALUE = 56
ERR_INVALID_OPERAND = 57
ERR_INTERPRET = 69
